### ISSUE TITLE
aligndrill parameters on FlatCAM 8.994 beta

### ISSUE THREAD

**Issue by sle118** [Gobol/FlatCAM_automation#1]
@Gobol, thank you for creating this script.

I am trying to leverage it for my own boards, exported from EasyEDA pro and so far so good with one exception; I am using FlatCAM 8.99 beta, and _**aligndrill**_ now has a new parameter called _minoffset_. I tried setting different values and also changing the axis, but somehow the operation ends up timing out and I am unsure what is going on.

do you have any hints on this?

**Comment by Gobol** [comment]
Yeah, sorry about that. I've forgotten to mention I'm using a slightly changed FlatCAM beta. 
First of all, you should use this version:
[flatcam_beta](https://bitbucket.org/marius_stanciu/flatcam_beta/src/Beta/)

Then, you should overwrite file TclCommandAlignDrill.py from `./tclCommands` to one included in this repo. I know it's kind of non-professional, but I don't have time to PR this to the marius_stanciu repo.

@sle118 give me a hint if you need some additional help

**Comment by sle118** [comment]
I managed to find the flatcam repo and setup the development environment with dependencies so I could debug for myself. Your script was a real eye opener since it made me realize that there was a lot TCL could do!

Thank you!
